### ISSUE TITLE
"command failed: No such device (-19)" when trying to put adapter into monitor mode

### ISSUE THREAD

**Issue by gemesa** [morrownr/Monitor_Mode#11]
Hi @morrownr, so far your [8821au-20210708](https://github.com/morrownr/8821au-20210708) driver and `start-mon.sh` script have been working really good but recently something broke in my setup. When I try to put my [adapter](https://www.tp-link.com/en/home-networking/high-gain-adapter/archer-t2u-plus/) into monitor mode I receive this:

```
$ iw dev
phy#4
	Interface wlp0s20f0u1
		ifindex 7
		wdev 0x400000001
		addr XX:XX:XX:XX:XX:XX
		type managed
		txpower -100.00 dBm

$ sudo ./start-mon.sh wlp0s20f0u1
 --------------------------------
    start-mon.sh 20230305
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
    name  -  wlp0s20f0u1
    type  -  managed
    state -  DOWN
    addr  -  XX:XX:XX:XX:XX:XX
 --------------------------------

 Do you want to set a new addr? [y/N] 

 --------------------------------
    start-mon.sh 20230305
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
command failed: No such device (-19)
    name  -  
command failed: No such device (-19)
    type  -  
Device "" does not exist.
    state -  
command failed: No such device (-19)
    addr  -  
command failed: No such device (-19)
    chan  -  
 --------------------------------

 Do you want to set the channel? [y/N] 
```

I am on Thinkpad laptop with Fedora 37. I tried 3 different kernels:
```
$ uname -a
Linux fedora 6.1.15-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  3 17:29:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ sudo grubby --info=ALL | grep -E "^kernel|^index"
index=0
kernel="/boot/vmlinuz-6.2.7-200.fc37.x86_64"
index=1
kernel="/boot/vmlinuz-6.1.18-200.fc37.x86_64"
index=2
kernel="/boot/vmlinuz-6.1.15-200.fc37.x86_64"
```

And tried to reinstall the driver with `sudo ./install-driver.sh` on all of the 3 kernels but no luck so far. Do you have any idea what is wrong?

**Comment by gemesa** [comment]
Ok, I found the rootcause. The name of my interface is `wlp0s20f0u1` but the script expects either `wlan0` or `wlan1`:

```
if [ "$iface0" = "wlan0" ]; then
	iface0mon="wlan0mon"
fi
if [ "$iface0" = "wlan1" ]; then
	iface0mon="wlan1mon"
fi
```

So `iface0mon` was empty in my case.

**Comment by gemesa** [comment]
> ```
> if [ "$iface0" = "wlan0" ]; then
> 	iface0mon="wlan0mon"
> fi
> if [ "$iface0" = "wlan1" ]; then
> 	iface0mon="wlan1mon"
> fi
> ```

What are your thoughts about rewriting this to be more generic? See the linked PR.

```
iface0mon="${iface0}mon"
```

**Comment by gemesa** [comment]
> Hi @morrownr, so far your [8821au-20210708](https://github.com/morrownr/8821au-20210708) driver and `start-mon.sh` script have been working really good but recently something broke in my setup.

Ok, I just noticed you have been working on interface renaming recently in https://github.com/morrownr/Monitor_Mode/commit/c5b13b5d4b3cfb817de62d55bc4133a044be9aff, this is what changed in my setup.

**Comment by morrownr** [comment]
Hi @gemesa 

> Do you have any idea what is wrong?

I think I do. It is just an idea and I have not tracked it down to the specific issue.

I had a couple of reports that were interesting in the Realtek driver repos. This led me to do some testing and you may remember me asking around earlier this year. During my testing, I noticed that the interface irregularities did not happen on two distros. RasPiOS and Kali. What do they have in common? Neither use `PREDICTABLE NETWORK INTERFACE NAMES`. As I turned that off in other distros, the problem would go away.

Here is a good bit of background info:

https://wiki.debian.org/NetworkInterfaceNames#initrd

This seems to have become a problem with kernels beyond a certain point. I can't say if is 6.1 or another but I do have the capability to test this try to narrow things down. It will probably be a few weeks until I can spend much time on this as I am packed and am moving.

Let me know if you come across anything because this is a challenge. I can see why it may not be getting too much attention yet because many people working with monitor mode are using Kali or they are not upgraded to a very recent kernel.

@morrownr

**Comment by morrownr** [comment]
> > ```
> > if [ "$iface0" = "wlan0" ]; then
> > 	iface0mon="wlan0mon"
> > fi
> > if [ "$iface0" = "wlan1" ]; then
> > 	iface0mon="wlan1mon"
> > fi
> > ```
> 
> What are your thoughts about rewriting this to be more generic? See the linked PR.
> 
> ```
> iface0mon="${iface0}mon"
> ```

I took at look at the code when the above msg came in. There is definitely a logic error in the code. Let me work this.

**Comment by morrownr** [comment]
```
# assign monitor mode interface name
#	info:	Realtek out-of-kernel drivers have problems when trying to rename
#		interfaces on some systems.
#	info:	The above may be corrected by turning off the following:
#		PREDICTABLE NETWORK INTERFACE NAMES
#	more info: https://wiki.debian.org/NetworkInterfaceNames#initrd
#	info:	Realtek out-of-kernel drivers do not handle deleting or adding
#		interface names. There is no virtual interface support.
#	info:	In-kernel drivers do not have the above problems.
#
	iface0mon="$iface0"
	if [ "iface0mon" = "wlan0" ]; then
		iface0mon="wlan0mon"
	fi
	if [ "iface0mon" = "wlan1" ]; then
		iface0mon="wlan1mon"
	fi
	ip link set dev "$iface0" name $iface0mon
```

That is my rework for now. If you have time to consolidate the 2 if-then's into something that works better, please do. I am busy the rest of the day.

**Comment by gemesa** [comment]
There are some $ missing which is [reported by shellcheck](https://github.com/morrownr/Monitor_Mode/actions/runs/4526122862/jobs/7971077662) also:
```
  In ./start-mon.sh line 154:
  	if [ "iface0mon" = "wlan0" ]; then
                           ^-- SC2050 (warning): This expression is constant. Did you forget the $ on a variable?
  
  
  In ./start-mon.sh line 157:
  	if [ "iface0mon" = "wlan1" ]; then
                           ^-- SC2050 (warning): This expression is constant. Did you forget the $ on a variable?
```

But other than that looks good.
