### ISSUE TITLE
Tenda U12 with concurrent mode.

### ISSUE THREAD

**Issue by Stroichik** [morrownr/Monitor_Mode#3]
Hello.
I tried script for Monitor Mode, and i still got weird results.
It does show in script info that channel is switched to what ever i choose, but when i do try to manually check channel - it reverts back to channel 1.

![image](https://user-images.githubusercontent.com/12185977/200380904-de0f3b93-1eb1-40ce-ad94-a815b61b88e2.png)

**Comment by Stroichik** [comment]
However, if i run hostapd for wlan0 with any channel of my choice, stop hostapd and set monitor mode again i get this.

Channels do change and keep that way. I dunno if maybe i do something wrong or that Tenda U12 is acting weird, but it does bother me somehow. Sorry for bothering you as well :)

![image](https://user-images.githubusercontent.com/12185977/200383691-70014bb4-391b-47ac-b594-edb003846050.png)

**Comment by Stroichik** [comment]
And then i try to use your script to change channel and still shows weird results.
Your script info shows channel 7 being set, but iw dev still shows channel 3 on interface.

![image](https://user-images.githubusercontent.com/12185977/200384345-813309d4-a4f1-48d9-a3b6-b59364a11eec.png)

**Comment by morrownr** [comment]
You need to get rid of the concurrent mode as it will lock the channel of the two interfaces.

Run:

$ sudo ./remove-driver.sh

and probably the easiest thing to do at this point is delete the driver directory and start over. Don't activate concurrent mode.

**Comment by Stroichik** [comment]
Hmm, but i really need concurrent mode for learning wifi pentest, since i dont have many wifi adapters.

And i think i somehow found some sort of bypass.
Its weird, but iwconfig can change channel no problem, while iw cannot. At least for me.

iwconfig cannot set monitor mode, though. But iw can. It looks funny, but i suppose i can just use iwconfig for channel switch commands for now. At least until i`ll get Alfa AWUS036ACM that i read about in your github.

![image](https://user-images.githubusercontent.com/12185977/200426516-7c13f7d7-6066-4253-a532-dfee60593b81.png)

**Comment by morrownr** [comment]
> but i really need concurrent mode for learning wifi pentest

From the Realtek docs:

```

Note: Concurrent Mode only supports 3 combinations

Station mode + Station mode
Station mode + AP mode
Station mode + P2P mode

```

I don't see monitor mode in there. Tell me what you want to do and we'll try to figure out a solution.

> iwconfig cannot set monitor mode

iwconfig has been depreciated for several years and I don't think it is maintained.

> until i`ll get Alfa AWUS036ACM that i read about in your github

I have an Alfa ACM and a ACHM. Both are good, high quality adapters. I mostly use the ACM for AP mode and managed mode. The ACHM is the one I use when I want to do monitor. The reason- it can reach out and touch things at a distance. It has range. Alfa should be out with 2 news adapters soon. One is a regular power adapter and the other will likely be a high power adapter or so the tea leaves are forecasting. Both of the new adapters will likely be based on the mt7921au, WiFi 6e chipset. I have had reports that the CF-953AX, mt7921au chipset, is doing really well with monitor mode so that is a good indication that the Alfa adapters will be really good.

**Comment by Stroichik** [comment]
Well, monitor mode does work somehow for Tenda U12. It has that mode in iw list and i can turn it on. Main problem was switching channels, and since iwconfig can do that - i can at least stop worrying about it.

Not sure when i'll be ready for real pentesting, still got much to learn. But at least i'll try to get Alfa beforehand for training on my own wifi. Thanks for awesome research on wifi adapters and chipsets. It really helps to figure out what i need to buy to have it work as intended.

**Comment by Stroichik** [comment]
Yeah, Tenda U12 is unable to do anything serious in concurrent mode. Simply doesnt work properly with any wifi scripts. Can do monitor and single interface attacks and thats mostly it. I hope i can get my hands on Alfa soon.

**Comment by morrownr** [comment]
It is actually on my to-do list to remove mention of concurrent mode from the README and to remove the scripts to activate it. Users will be able to activate it in the Makefile but I have yet to find a user that can find a use for it and all it does is cause me support problems.

**Comment by Stroichik** [comment]
Well it was experience nontheless. Now i better know what to look for in adapters if i'll need to get one. So maybe dont delete concurrent mode and script, but just mark it in Readme somehow, that it won't be helpful for attacks in most cases. I think i'll keep my Tenda U12 and use it for Victim VM live-target practice when i'll get proper adapter in future.
